[package]
name = "cc-rs-utils"
authors=["cc heart"]
version = "0.1.0"
edition = "2021"

license = "MIT"

[[test]]
name = "integration_tests"
path = "tests/integration_tests.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
